#!/bin/bash

set -e

cd $HOME/ed3/ed3-demo/echo/

#LOGGING=-Djava.util.logging.config.file=../logging.properties
LOGGING=

$HOME/sw/jdk/bin/java ${LOGGING} -cp target/dependency/\*:target/ed3-demo-echo-1.0-SNAPSHOT.jar ed3.demo.echo.WorkAllDatasets

